// Gets all users in db
GET http://localhost:3000/users

###
// Gets specific users in db
GET http://localhost:3000/users/6147af6be02c1b2c38163edf

###
// Adds users to db
POST http://localhost:3000/users
Content-Type: application/json

{
  "username": "june",
  "password": "bigBrain"
}

###
// Deletes specific users from db
DELETE http://localhost:3000/users/6147af6be02c1b2c38163edf

###
// Adds users to db
POST http://localhost:3000/users/login
Content-Type: application/json

{
  "username": "june",
  "password": "bigBrain"
}
